version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  Install:
    - location: /scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: /scripts/generate_docker
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /scripts/run_docker
      timeout: 300
      runas: root
