version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  ApplicationStop:
    = location: /scripts/stop_dockers
      timeout: 300
      runas: root
  Install:
    - location: /scripts/generate_docker
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /scripts/run_docker
      timeout: 300
      runas: root
