version: 0.0
os: linux
files:
  - source: /
    destination: /ezops
hooks:  
  ApplicationStop:
    - location: /scripts/stop_docker
      timeout: 300
      runas: root
  AfterInstall:
    - location: /scripts/generate_docker
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /scripts/run_docker
      timeout: 300
      runas: root
