version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  Install:
    - location: /scripts/install_dependencies
      timeout: 300
  AfterInstall:
    - location: /scripts/generate_docker
      timeout: 300
  ApplicationStart:
    - location: /scripts/run_docker
      timeout: 300
