version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies
      timeout: 300
    - location: /scripts/generate_docker
      timeout: 300
  ApplicationStop:
    - location: /scripts/run_docker
      timeout: 300
