version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  Install:
    - location: /app/scripts/generate_docker
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /app/scripts/run_docker
      timeout: 300
      runas: root
