name: deploy

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{  secrets.AWS_SECRET_ACCESS_KEY  }}
        aws-region: ${{ secrets.AWS_REGION }}
    - run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b6i4m2g2
    - run: docker build -t ezops-app .
    - run: docker tag ezops-app:latest public.ecr.aws/b6i4m2g2/ezops-app:latest
    - run: docker push public.ecr.aws/b6i4m2g2/ezops-app:latest